apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-app
  labels:
    app: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure-container
        image: shaurya93/medicure:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  type: NodePort
  selector:
    app: medicure
  ports:
    - protocol: TCP
      port: 8080        # service port
      targetPort: 8080  # container port
      nodePort: 30080   # external port to access via worker public IP

